defmodule Contour.Repo.Migrations.Foundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:oidc_attempts, primary_key: false) do
      add :state_hash, :binary, null: false, primary_key: true
      add :expires_at, :utc_datetime_usec, null: false
    end

    create table(:rate_limit_buckets, primary_key: false) do
      add :key, :binary, null: false, primary_key: true
      add :window, :bigint, null: false, primary_key: true
      add :count, :bigint, null: false
      add :expires_at, :bigint, null: false
    end

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create unique_index(:sessions, [:token_hash], name: "sessions_token_index")

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sessions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "sessions_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :oidc_issuer, :text, null: false
      add :oidc_subject, :text, null: false
      add :email, :text, null: false
      add :display_name, :text, null: false
      add :disabled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:oidc_issuer, :oidc_subject], name: "users_oidc_identity_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:oidc_issuer, :oidc_subject],
                     name: "users_oidc_identity_index"
                   )

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :disabled_at
      remove :display_name
      remove :email
      remove :oidc_subject
      remove :oidc_issuer
    end

    drop constraint(:sessions, "sessions_user_id_fkey")

    alter table(:sessions) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop_if_exists unique_index(:sessions, [:token_hash], name: "sessions_token_index")

    drop table(:sessions)

    drop table(:rate_limit_buckets)

    drop table(:oidc_attempts)
  end
end
