defmodule ContourWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :contour

  # Only the opaque session token and OIDC challenge live in the encrypted cookie.
  @session_options [
    store: :cookie,
    key: "_contour_key",
    signing_salt: "485miyj/",
    encryption_salt: "contour-encrypted-session-v1",
    secure: Application.compile_env(:contour, :secure_cookies),
    http_only: true,
    max_age: 43_200,
    same_site: "Lax"
  ]

  socket "/socket", ContourWeb.UserSocket, websocket: [max_frame_size: 4096], longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], max_frame_size: 16_384],
    longpoll: false

  plug ContourWeb.Health
  plug ContourWeb.Plugs.RequestGate

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :contour,
    gzip: not code_reloading?,
    only: ContourWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :contour
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: [],
    length: 16_384,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ContourWeb.Router
end
