apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contour-web
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: contour
      app.kubernetes.io/component: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contour-core
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: contour
      app.kubernetes.io/component: core
