apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - cnpg.yaml
  - web.yaml
  - core.yaml
  - services.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
  - migration.yaml
  - distribution-tls.yaml
